// Code generated by http://www.gotool.top
package model

import "time"

type InDay struct {
	Date  time.Time `gorm:"column:date;primary_key;NOT NULL" json:"date"`
	Money float32   `gorm:"column:money;default:NULL;comment:'时间'" json:"money"`
}

func (i *InDay) TableName() string {
	return "in_day"
}
