// Code generated by http://www.gotool.top
package model

type InMonth struct {
	Date  string `gorm:"column:date;primary_key;NOT NULL" json:"date"`
	Money float32 `gorm:"column:money;default:NULL;comment:'金额'" json:"money"`
}

func (i *InMonth) TableName() string {
	return "in_month"
}
