// Code generated by http://www.gotool.top
package model

import (
	"time"
)

type OutRecords struct {
	Id     int32     `gorm:"column:id;primary_key;NOT NULL" json:"id"`
	Money  float32   `gorm:"column:money;default:NULL;comment:'金额'" json:"money"`
	Remark string    `gorm:"column:remark;default:NULL;comment:'备注'" json:"remark"`
	Date   time.Time `gorm:"column:date;default:NULL;comment:'时间'" json:"date"`
}

func (o *OutRecords) TableName() string {
	return "out_records"
}
