// Code generated by http://www.gotool.top
package model

type OutMonth struct {
	Date  string `gorm:"column:date;primary_key;NOT NULL" json:"date"`
	Money float32 `gorm:"column:money;default:NULL;comment:'时间'" json:"money"`
}

func (o *OutMonth) TableName() string {
	return "out_month"
}
