// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"mall-admin/rpc/admin"
	"mall-admin/rpc/internal/logic"
	"mall-admin/rpc/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// api 授权
func (s *AuthServer) ApiAuth(ctx context.Context, in *admin.ApiAuthReq) (*admin.ApiAuthResp, error) {
	l := logic.NewApiAuthLogic(ctx, s.svcCtx)
	return l.ApiAuth(in)
}
